azure_dnsresolver_dns_forwarding_rulesets
azure_dnsresolver_dns_resolvers
azure_dns_zones
azure_dns_record_sets
azure_privatedns_private_zones
azure_privatedns_private_zone_record_sets
azure_privatedns_private_zone_virtual_network_links