apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  platform: gcp
  generationRules:
    - resourceTypes:
        - gcp_iam_service_account
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: [name]
          mode: substring
      slxs:
        - baseName: gcp-iam-serviceaccount-health
          qualifiers: ["project"]
          baseTemplateName: gcp-iam-serviceaccount-health
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: sli
            - type: runbook
              templateName: gcp-iam-serviceaccount-health-taskset.yaml
