apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  platform: vast_data
  generationRules:
    - resourceTypes:
        - vast_data_tenant
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: ["name"]
          mode: substring
      slxs:
        - baseName: vast-tenant-storage
          qualifiers: ["cluster", "tenant"]
          baseTemplateName: vast-tenant-storage-health
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: sli
            - type: runbook
              templateName: vast-tenant-storage-health-taskset.yaml
