apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  platform: gcp
  generationRules:
    - resourceTypes:
        - gcp_cloud_run_service
        - gcp_cloud_run_revision
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: [project_id]
          mode: substring
      slxs:
        - baseName: gcp-cloudrun-service-health
          qualifiers: ["project"]
          baseTemplateName: gcp-cloudrun-service-health
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: sli
            - type: runbook
              templateName: gcp-cloudrun-service-health-taskset.yaml
