# -----------------------------------------------------------------------------
# gcp-cloud-sql-performance -- Test Infrastructure
#
# Provisions Cloud SQL fixtures covering the CodeBundle's detection scenarios:
#   1. sql-healthy - healthy instance (low utilization, autoresize, adequate disk)
#   2. sql-overutilized - instance whose utilization tends high (small/fixed tier,
#      disk fill risk) to exercise the utilization and storage checks
#
# Cloud Monitoring and logging generated by real traffic drive the metric and
# slow-query detection, so metric-based issue presence depends on load being
# generated in the test project.
# -----------------------------------------------------------------------------

locals {
  suffix = var.resource_suffix
}

# -----------------------------------------------------------------------------
# Scenario 1: healthy Cloud SQL instance (MySQL, fixed smaller disk, autoresize)
# -----------------------------------------------------------------------------
resource "google_sql_database_instance" "healthy" {
  name             = "sql-perf-healthy-${local.suffix}"
  region           = var.region
  database_version = "MYSQL_8_0"
  deletion_protection = false

  settings {
    tier              = "db-f1-micro"
    disk_size         = 20
    disk_autoresize   = true
    disk_type         = "PD_SSD"
    availability_type = "ZONAL"
  }
}

resource "google_sql_database" "healthy_db" {
  name     = "sqlperfhealthydb"
  instance = google_sql_database_instance.healthy.name
}

# -----------------------------------------------------------------------------
# Scenario 2: over-utilized instance - small tier, no autoresize, larger disk
# fill so it exercises the storage-fill-at-risk and utilization checks
# -----------------------------------------------------------------------------
resource "google_sql_database_instance" "overutilized" {
  name             = "sql-perf-overutilized-${local.suffix}"
  region           = var.region
  database_version = "MYSQL_8_0"
  deletion_protection = false

  settings {
    tier              = "db-f1-micro"
    disk_size         = 50
    disk_autoresize   = false
    disk_type         = "PD_SSD"
    availability_type = "ZONAL"
  }
}

resource "google_sql_database" "overutilized_db" {
  name     = "sqlperfoverutilizeddb"
  instance = google_sql_database_instance.overutilized.name
}
