apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  platform: aws
  generationRules:
    - resourceTypes:
        - aws_sqs_queues
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: ["name"]
          mode: substring
      slxs:
        - baseName: aws-sqs-dlq-health
          qualifiers: ["account", "region", "resource"]
          baseTemplateName: aws-sqs-dlq-health
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: runbook
              templateName: aws-sqs-dlq-health-taskset.yaml
