apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  platform: gcp
  generationRules:
    - resourceTypes:
        - cloudfunctions.googleapis.com/CloudFunction
        - cloudfunctions.googleapis.com/Function
        - gcp_functions_functions
        - gcp_functionsv2_functions
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: [project_id]
          mode: substring
      slxs:
        - baseName: gcp-function-health
          qualifiers: ["project"]
          baseTemplateName: gcp-cloud-function-health
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: sli
            - type: slo
            - type: runbook
              templateName: gcp-cloud-function-health-taskset.yaml
