apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
    - resourceTypes:
        - namespace
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: [name]
          mode: substring
      slxs:
        - baseName: af-wl-diag
          qualifiers: ["namespace", "cluster"]
          baseTemplateName: k8s-airflow-workload-diagnostics
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: sli
            - type: runbook
              templateName: k8s-airflow-workload-diagnostics-taskset.yaml
