#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Offline assertion tier for gcp-apigee-security-config.
#
# Runs every check script against canned Apigee Management API and Cloud
# Monitoring responses -- no cloud, no credentials, no spend -- and ASSERTS on
# what it reports. Exits non-zero if any assertion fails, so it can gate a PR.
#
# The fixtures under .test/offline/fixtures/ are generated by fixtures.sh from
# the Apigee v1 discovery document, never from what the code expects to see. Read
# the header of that file before changing one.
#
# This tier cannot catch anything that depends on real API behaviour not encoded
# in the fixtures; it complements a live run, it does not replace it.
#
#   ./run.sh          run every scenario
#   ./run.sh -v       also echo each script's stdout on failure
# -----------------------------------------------------------------------------
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUNDLE="$(cd "${HERE}/../.." && pwd)"
WORK="${HERE}/.work"
VERBOSE="${1:-}"

RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; BLUE=$'\033[0;34m'; DIM=$'\033[2m'; NC=$'\033[0m'
PASS=0
FAIL=0

ok()  { PASS=$((PASS + 1)); printf '    %sPASS%s %s\n' "${GREEN}" "${NC}" "$1"; }
bad() { FAIL=$((FAIL + 1)); printf '    %sFAIL%s %s\n' "${RED}" "${NC}" "$1"; }

assert_eq() {
    if [ "$2" = "$3" ]; then ok "$1"; else bad "$1 ${DIM}(expected '$3', got '$2')${NC}"; fi
}
assert_has() {
    case "$2" in *"$3"*) ok "$1" ;; *) bad "$1 ${DIM}(missing '$3')${NC}" ;; esac
}
assert_hasnt() {
    case "$2" in *"$3"*) bad "$1 ${DIM}(unexpectedly found '$3')${NC}" ;; *) ok "$1" ;; esac
}

CHECKS="check_quota_limits check_app_access check_security_score check_target_vhost_config"

issuefile_for() {
    case "$1" in
        check_quota_limits)        echo "quota_limits_issues.json" ;;
        check_app_access)          echo "app_access_issues.json" ;;
        check_security_score)      echo "security_score_issues.json" ;;
        check_target_vhost_config) echo "target_vhost_issues.json" ;;
    esac
}

issues() { [ -f "$1" ] && jq 'length' "$1" 2>/dev/null || echo -1; }
titles() { [ -f "$1" ] && jq -r '[.[].title] | join(" | ")' "$1" 2>/dev/null || echo ""; }
# Whole issue body -- titles are failure-mode only, so anything asserting on a
# resource name has to look at details/actual as well.
bodies() { [ -f "$1" ] && jq -r '[.[] | .title, .actual, .details] | join(" ")' "$1" 2>/dev/null || echo ""; }

# scenario <name> <fixture-dir> [extra env assignments...]
scenario() {
    local name="$1" fixtures="$2"; shift 2
    printf '\n%s== %s%s\n' "${BLUE}" "${name}" "${NC}"
    rm -rf "${WORK}"; mkdir -p "${WORK}"; cd "${WORK}" || exit 1
    export PATH="${HERE}/bin:${PATH}"
    export FIXTURES="${fixtures}"
    export APIGEE_ORG="test-org"
    export GCP_PROJECT_ID="test-project"
    export QUOTA_ABUSE_THRESHOLD=1000000
    export SECURITY_SCORE_THRESHOLD=80
    export SECURITY_WINDOW_HOURS=6
    for s in ${CHECKS}; do
        env "$@" bash "${BUNDLE}/${s}.sh" > "${s}.log" 2>&1
        eval "RC_${s}=\$?"
    done
}
rc() { eval "echo \"\${RC_$1}\""; }

bash "${HERE}/fixtures.sh" "${HERE}/fixtures/main" test-org >/dev/null

# =============================================================================
scenario "Scenario A -- seeded org, every failure mode present" "${HERE}/fixtures/main"
for s in ${CHECKS}; do assert_eq "${s} exits 0" "$(rc "${s}")" "0"; done

printf '  %sone finding per failure mode, never per resource%s\n' "${DIM}" "${NC}"
# 4 products: product-open (no quota), product-huge (excessive), product-auto
# (no quota AND auto), product-ok (clean). Three failure modes are present, so
# three issues -- NOT one per offending product, of which there are four.
assert_eq "quota: three failure modes -> three issues" \
    "$(issues quota_limits_issues.json)" "3"
assert_has "  no-quota mode fired"   "$(titles quota_limits_issues.json)" "have no quota configured"
assert_has "  excessive-quota fired" "$(titles quota_limits_issues.json)" "have an excessive quota"
assert_has "  auto-approval fired"   "$(titles quota_limits_issues.json)" "auto-approve access requests"

# Both offending products must be named INSIDE the single no-quota issue.
NOQUOTA="$(jq -r '[.[] | select(.title | test("no quota configured")) | .details, .actual] | join(" ")' \
    quota_limits_issues.json 2>/dev/null || echo "")"
assert_has "  no-quota issue lists product-open"  "${NOQUOTA}" "product-open"
assert_has "  no-quota issue lists product-auto"  "${NOQUOTA}" "product-auto"
assert_hasnt "  ...and not the healthy product"   "${NOQUOTA}" "product-ok"

# 3 app-access failure modes across 3 apps.
assert_eq "app access: three failure modes -> three issues" \
    "$(issues app_access_issues.json)" "3"
assert_has "  over-broad app scope fired"  "$(titles app_access_issues.json)" "developer apps declare over-broad scopes"
assert_has "  over-broad key scope fired"  "$(titles app_access_issues.json)" "consumer keys carry over-broad scopes"
assert_has "  revoked key fired"           "$(titles app_access_issues.json)" "Revoked Apigee consumer keys"

# A revoked key carries wildcard scopes in the fixtures. It must be counted as a
# stale key, NOT as a live over-broad credential -- a revoked key grants nothing.
BROADKEY="$(jq -r '[.[] | select(.title | test("consumer keys carry over-broad")) | .details] | join(" ")' \
    app_access_issues.json 2>/dev/null || echo "")"
assert_hasnt "  a revoked wildcard key is not counted as a live one" \
    "${BROADKEY}" "app-stale"

# Consumer keys are credentials. Only a short prefix may ever be recorded.
assert_hasnt "no full consumer key anywhere in the issues" \
    "$(bodies app_access_issues.json)" "CONSUMERKEYAAAA1111"
assert_has   "  ...only a truncated prefix" \
    "$(bodies app_access_issues.json)" "CONSUMER..."

printf '  %starget server TLS is read from the per-server document%s\n' "${DIM}" "${NC}"
# The defect this fixture set exists for. The list endpoint is a bare array of
# STRINGS and carries no sSLInfo; the previous code read .sSLInfo off those
# strings, got nothing, and flagged EVERY target server as plaintext -- including
# ts-secure, which has TLS enabled.
assert_eq  "one plaintext finding, not one per target server" \
    "$(issues target_vhost_issues.json)" "1"
TLSBODY="$(bodies target_vhost_issues.json)"
assert_has  "  the plaintext target is named"          "${TLSBODY}" "ts-plain"
assert_has  "  the explicitly-disabled target is too"  "${TLSBODY}" "ts-disabled"
assert_hasnt "  the TLS-enabled target is NOT flagged" "${TLSBODY}" "ts-secure"

printf '  %ssecurity metrics: measured is a finding, unmeasured is not%s\n' "${DIM}" "${NC}"
# score 55 < 80 -> fires. detected 20 > 0 -> fires. incident metric absent ->
# must raise NOTHING: absence means Advanced API Security did not measure it,
# which is not the same as measuring zero risk.
assert_eq  "security: two measured modes -> two issues" \
    "$(issues security_score_issues.json)" "2"
assert_has "  low score fired"       "$(titles security_score_issues.json)" "security score is below"
assert_has "  detected traffic fired" "$(titles security_score_issues.json)" "detected abusive traffic"
assert_hasnt "  an UNMEASURED metric raises nothing" \
    "$(titles security_score_issues.json)" "open security incidents"

printf '  %sissue titles: failure mode + org scope only%s\n' "${DIM}" "${NC}"
# A title may name the SLX's own scope: there is exactly one org per SLX and it
# never changes, so it costs no churn and tells an operator which SLX fired. It
# must NOT name a CONTAINED resource, of which there are many and which come and
# go, nor any changing number -- a score, a quota or a request count in a title
# opens and closes an issue on every run.
#
# The org is stripped before the checks below so it does not count as a contained
# resource name; it is stripped only where backticked, so an unquoted mention
# would still trip the guard.
strip_scope() {
    jq -r '[.[].title
            | gsub(" in org `[^`]*`"; "")
            | gsub("`test-org`"; "")]'
}
for f in quota_limits app_access security_score target_vhost; do
    [ -f "${f}_issues.json" ] || continue
    assert_eq "${f}: every title names the org scope" \
        "$(jq -r '[.[].title | select(test("`test-org`") | not)] | length' "${f}_issues.json")" "0"
    assert_eq "${f}: no contained resource name in any title" \
        "$(strip_scope < "${f}_issues.json" | jq -r '[.[] | select(test("product-|app-|ts-|dev-[ab]@|env-prod|env-stage|CONSUMER|test-org"))] | length')" "0"
    assert_eq "${f}: no digits outside the scope" \
        "$(strip_scope < "${f}_issues.json" | jq -r '[.[] | select(test("[0-9]"))] | length')" "0"
done

# =============================================================================
# Failure to determine must NOT look like a positive determination of absence.
scenario "Scenario B -- no token (could NOT determine)" "${HERE}/fixtures/main" GCLOUD_NO_TOKEN=1
for s in ${CHECKS}; do
    assert_eq "${s} exits 0" "$(rc "${s}")" "0"
    assert_eq "${s} raises exactly one issue rather than reporting clean" \
        "$(issues "$(issuefile_for "${s}")")" "1"
    assert_has "${s} says it could not read anything" \
        "$(titles "$(issuefile_for "${s}")")" "Cannot read Apigee"
done

# =============================================================================
# ...and a genuinely empty org must NOT be reported as a fault. This is the
# other half of the same distinction, and getting it wrong the other way turns
# every unused org into a page.
prepare_empty() {
    rm -rf "${HERE}/fixtures/empty"; cp -R "${HERE}/fixtures/main" "${HERE}/fixtures/empty"
    echo '{"apiProduct":[]}' > "${HERE}/fixtures/empty/organizations_test-org_apiproducts.json"
    echo '{"developer":[]}'  > "${HERE}/fixtures/empty/organizations_test-org_developers.json"
    echo '[]'                > "${HERE}/fixtures/empty/organizations_test-org_environments.json"
    echo '{}'                > "${HERE}/fixtures/empty/_monitoring_score.json"
    echo '{}'                > "${HERE}/fixtures/empty/_monitoring_detected_request_count.json"
}
prepare_empty
scenario "Scenario C -- org with nothing configured (absence is not a finding)" "${HERE}/fixtures/empty"
for s in ${CHECKS}; do
    assert_eq "${s} exits 0" "$(rc "${s}")" "0"
    assert_eq "${s} reports no issue" "$(issues "$(issuefile_for "${s}")")" "0"
done

# =============================================================================
# A healthy org: everything present, nothing wrong. Proves the checks are capable
# of passing, so Scenario A's findings are not just "always fires".
prepare_healthy() {
    rm -rf "${HERE}/fixtures/healthy"; cp -R "${HERE}/fixtures/main" "${HERE}/fixtures/healthy"
    cat > "${HERE}/fixtures/healthy/organizations_test-org_apiproducts.json" <<'EOF'
{"apiProduct":[{"name":"product-ok","approvalType":"manual","quota":"1000","quotaInterval":"1","quotaTimeUnit":"minute"}]}
EOF
    cat > "${HERE}/fixtures/healthy/organizations_test-org_developers.json" <<'EOF'
{"developer":[{"email":"dev-a@example.com","developerId":"id-a","status":"active"}]}
EOF
    cat > "${HERE}/fixtures/healthy/organizations_test-org_developers_dev-a@example.com_apps.json" <<'EOF'
{"app":[{"name":"app-tidy"}]}
EOF
    echo '["env-prod"]' > "${HERE}/fixtures/healthy/organizations_test-org_environments.json"
    echo '["ts-secure"]' > "${HERE}/fixtures/healthy/organizations_test-org_environments_env-prod_targetservers.json"
    cat > "${HERE}/fixtures/healthy/_monitoring_score.json" <<'EOF'
{"timeSeries":[{"points":[{"value":{"doubleValue":95}}]}]}
EOF
    echo '{}' > "${HERE}/fixtures/healthy/_monitoring_detected_request_count.json"
}
prepare_healthy
scenario "Scenario D -- healthy org (checks must be able to pass)" "${HERE}/fixtures/healthy"
for s in ${CHECKS}; do
    assert_eq "${s} exits 0" "$(rc "${s}")" "0"
    assert_eq "${s} finds nothing" "$(issues "$(issuefile_for "${s}")")" "0"
done

# =============================================================================
# Wiring this tier cannot exercise behaviourally -- it runs the scripts directly,
# never `robot` -- so it is checked statically instead.
printf '\n%s== Scenario E -- generation rule and templates (static)%s\n' "${BLUE}" "${NC}"
cd "${HERE}" || exit 1
RB="${BUNDLE}/runbook.robot"
GR="${BUNDLE}/.runwhen/generation-rules/gcp-apigee-security-config.yaml"

# Comments are stripped FIRST throughout. The rule's and templates' own
# commentary quotes the very expressions being forbidden -- including both
# qualifier forms and project.name -- so matching the whole file passes even with
# the change reverted. That is an assertion which cannot fail, which is worse
# than no assertion at all.
GR_CODE="$(grep -v '^ *#' "${GR}")"
assert_has  "generation rule gates on the Apigee organization" \
    "${GR_CODE}" "gcp_apigee_organizations"
assert_has  "  ...anchored on the organization" \
    "${GR_CODE}" 'qualifiers: ["resource"]'
# gcp-hierarchy.yaml inserts project_id into the path ONLY when `resource` is a
# qualifier, so the old ["project"] flattened resourcePath from
# gcp/<project>/<org> to gcp/<project> and never named the org at all.
assert_hasnt "  ...not flattened back to the project" \
    "${GR_CODE}" 'qualifiers: ["project"]'
# ["project", "resource"] renders <project>-<project>-...-<hash>, because an
# Apigee X org is named after its GCP project.
assert_hasnt "  ...not doubled up with the project" \
    "${GR_CODE}" 'qualifiers: ["project", "resource"]'

printf '  %sruns runbook-only%s\n' "${DIM}" "${NC}"
assert_hasnt "no SLI in outputItems" "${GR_CODE}" "type: sli"
assert_hasnt "no SLO in outputItems" "${GR_CODE}" "type: slo"
assert_eq "no sli.robot ships" \
    "$([ -e "${BUNDLE}/sli.robot" ] && echo present || echo absent)" "absent"
assert_eq "no SLI template ships" \
    "$(find "${BUNDLE}/.runwhen/templates" -name '*-sli.yaml' | wc -l | xargs)" "0"
assert_eq "no SLO template ships" \
    "$(find "${BUNDLE}/.runwhen/templates" -name '*-slo.yaml' | wc -l | xargs)" "0"
# Deleting the SLI must not take a check with it. Asserted on script names so the
# coverage claim is checked rather than trusted. check_keystore_tls.sh is
# deliberately absent -- see the README -- and is asserted separately below.
for s in check_quota_limits check_app_access check_security_score check_target_vhost_config; do
    assert_has "${s}.sh, which the SLI scored, is still run by a runbook task" \
        "$(cat "${RB}")" "bash_file=${s}.sh"
done
# The one script the SLI scored that this bundle no longer ships. Its removal is
# a decision, not an oversight: the sibling gcp-apigee-environment-health bundle
# checks keystore alias expiry in check_keystore_cert_expiry.sh and gates on the
# SAME resource type, so keeping it here raised the same finding twice against
# two SLXs for one org.
assert_eq "keystore expiry is deliberately NOT duplicated here" \
    "$([ -e "${BUNDLE}/check_keystore_tls.sh" ] && echo present || echo absent)" "absent"
assert_has "  ...and the reason is written down next to the tasks" \
    "$(cat "${RB}")" "check_keystore_cert_expiry.sh"

for t in slx taskset; do
    TPLF="${BUNDLE}/.runwhen/templates/gcp-apigee-security-config-${t}.yaml"
    TPL="$(grep -v '^ *#' "${TPLF}")"
    # The bug this bundle shipped with: APIGEE_ORG was {{project.name}}. That
    # works by coincidence on Apigee X, where the org ID IS the project ID,
    # which is exactly why it survives testing and fails on any divergence --
    # an explicit override, hybrid, or legacy Edge. Checked on the value line
    # that follows the key, because GCP_PROJECT_ID legitimately uses project.name.
    ORGVAL="$(grep -A1 'name: APIGEE_ORG' "${TPLF}" | grep 'value:')"
    # shellcheck disable=SC2016
    assert_has   "${t}: APIGEE_ORG is the resolved org" "${ORGVAL}" "value: '{{apigee_org}}'"
    assert_hasnt "${t}: APIGEE_ORG is not the project"  "${ORGVAL}" "project.name"
    # The sibling traffic bundle's bug: match_resource.resource_name is not an
    # attribute runwhen-local builds, and CustomUndefined.__str__ returns a
    # placeholder rather than "", so it renders a literal
    # `missing_workspaceInfo_custom_variable`.
    assert_hasnt "${t}: never reads the non-existent match_resource.resource_name" \
        "${TPL}" "match_resource.resource_name"
    # BOOLEAN mode is the whole point. Plain default() substitutes only for an
    # UNDEFINED value, so a workspaceInfo carrying `apigee_org: ""` renders
    # APIGEE_ORG empty and skips every fallback.
    # shellcheck disable=SC2016
    assert_has "${t}: org fallback is in boolean mode, not undefined-only" \
        "${TPL}" 'default(_res.name, true)'
    # The indexed payload must be materialised before its fields are read.
    # CustomUndefined subclasses plain Undefined, whose __getattr__ RAISES, so
    # reaching through match_resource.resource.name aborts the whole render with
    # UndefinedError when .resource is absent rather than falling through.
    # shellcheck disable=SC2016
    assert_has "${t}: indexed payload is materialised before use" \
        "${TPL}" 'match_resource.resource | default({}, true)'
    # shellcheck disable=SC2016
    assert_hasnt "${t}: never reaches through .resource.name in an expression" \
        "${TPL}" 'default(match_resource.resource.name'
    # gcp-tags.yaml renders the resource_name tag from qualifiers.resource, so
    # sharing that source is what stops the tag and APIGEE_ORG disagreeing.
    # shellcheck disable=SC2016
    assert_has "${t}: org falls back to the same source as the resource_name tag" \
        "${TPL}" 'default(qualifiers.resource, true)'
done

# This bundle had NO scope tag at all. The SLX is anchored on the org, so it says
# so -- lowercase, which is the collection's vocabulary for this tag.
SLX_TAGS="$(grep -A1 'name: scope' "${BUNDLE}/.runwhen/templates/gcp-apigee-security-config-slx.yaml")"
assert_has   "SLX has a scope tag, and it is the organization" "${SLX_TAGS}" "value: organization"
assert_hasnt "  ...and not capitalised"                        "${SLX_TAGS}" "value: Organization"

# =============================================================================
printf '\n%s== Scenario F -- runbook wiring (static)%s\n' "${BLUE}" "${NC}"
TASK_TITLES="$(awk '/^\*\*\* Tasks \*\*\*/{f=1;next} /^\*\*\* Keywords/{f=0} f && /^[^ \t#]/ && NF' "${RB}")"
# Task names are substituted from config_provided, NOT from Robot suite
# variables, so ${APIGEE_ORG} in a title only resolves because it is a
# config_provided key. Set Suite Variable would not work here.
# shellcheck disable=SC2016
assert_eq "every task title names the org" \
    "$(printf '%s\n' "${TASK_TITLES}" | grep -c 'in `${APIGEE_ORG}`')" "4"
# The security score task used to name the project. The org is what the SLX
# covers, and it is what every other task named.
assert_eq "no task title still names the project" \
    "$(printf '%s\n' "${TASK_TITLES}" | grep -c 'GCP_PROJECT_ID' || true)" "0"
assert_eq "four check tasks remain" \
    "$(printf '%s\n' "${TASK_TITLES}" | wc -l | xargs)" "4"
# The summary task raised no finding at all -- it only restated what the other
# tasks had already reported, as an extra entry in the task list.
assert_eq "the summary is not a task" \
    "$(printf '%s\n' "${TASK_TITLES}" | grep -c '^Generate' || true)" "0"
assert_eq "and its script no longer ships" \
    "$([ -e "${BUNDLE}/generate_security_summary.sh" ] && echo present || echo absent)" "absent"

printf '  %sauth: tolerant activation, strict token probe%s\n' "${DIM}" "${NC}"
# Gating on the activation exit code took a whole run down -- every task NOT RUN
# -- on a runner whose ambient identity was fine, because gcloud misread the key
# file as a .p12. Activation stays tolerant; the token probe does not, so a run
# with no identity at all still cannot report green.
#
# The single quotes below are load-bearing, not a style slip: these are Robot
# ${...} literals to match verbatim. Letting the shell expand them yields an
# empty needle, which every assert_has then "passes" against. SC2016 is exactly
# backwards here, so it is disabled per assertion rather than fixed.
# shellcheck disable=SC2016
assert_has "activation is tolerant" \
    "$(cat "${RB}")" 'activate-service-account --key-file="./${gcp_credentials.key}" || true'
# Match the gate itself, not the bare sentinel: TOKEN_ABSENT also appears in the
# probe's own `echo`, so asserting the word alone survives deleting the IF.
# shellcheck disable=SC2016
assert_has "the token probe is what gates the suite" \
    "$(cat "${RB}")" 'IF    "TOKEN_ABSENT" in """${token.stdout}"""'
assert_has "no obtainable token fails the suite" \
    "$(cat "${RB}")" "Fail    Could not obtain a GCP access token"
# shellcheck disable=SC2016
assert_hasnt "the suite does not gate on the activation returncode" \
    "$(cat "${RB}")" 'IF    ${auth.returncode} != 0'
# shellcheck disable=SC2016
assert_has "the auth failure issue reports the key shape" \
    "$(cat "${RB}")" 'key file shape: ${keyshape.stdout}'

# =============================================================================
# Every variable the README documents as operator configuration must actually be
# wired through, in ALL THREE places the platform needs it:
#
#   taskset configProvided   the SLX supplies the value
#   Import User Variable     the suite accepts it
#   the ${env} dict          the scripts can see it
#
# This is a CLASS assertion, not another instance. SECURITY_WINDOW_HOURS was
# documented in the README and read by check_security_score.sh with a built-in
# default, but wired through none of the three -- so the built-in was the only
# reachable value and an operator following the README could not change it.
# Nothing was broken at the default, which is exactly why it survived: every
# behavioural assertion in this file passed while the promise was unkeepable.
#
# The behavioural scenarios cannot catch this, and adding more of them would not
# help: they export the variables themselves, so the scripts always see a value
# whether or not the runbook would ever supply one. They test each script's USE
# of a variable, never the platform's ability to SET it. Only a static check
# closes that gap.
#
# Scoped to the README's `## Configuration` section and to leading bullets, so
# prose mentions elsewhere -- KEY_JSON, TOKEN_ABSENT, and the thresholds named in
# the task descriptions -- are not mistaken for operator config. Genuinely
# internal variables (APIGEE_API) are not documented there and are correctly
# ignored.
printf '\n%s== Scenario G -- documented config is actually wired (static)%s\n' "${BLUE}" "${NC}"
TS="${BUNDLE}/.runwhen/templates/gcp-apigee-security-config-taskset.yaml"
# The backticks in the sed pattern are literal markdown, not a command
# substitution, so the single quotes are required. SC2016 is backwards here.
# shellcheck disable=SC2016
DOCUMENTED="$(awk '/^## Configuration/{f=1;next} /^## /{f=0} f' "${BUNDLE}/README.md" \
    | sed -n 's/^- `\([A-Z][A-Z0-9_]*\)`.*/\1/p' | sort -u)"
# Guard the extraction itself: a README refactor that renames the heading would
# silently yield an empty list, and every loop below would then vacuously pass.
assert_eq "the README's configuration list was found and is non-empty" \
    "$([ -n "${DOCUMENTED}" ] && echo yes || echo no)" "yes"
while IFS= read -r v; do
    [ -z "${v}" ] && continue
    assert_eq "${v}: supplied by the SLX (taskset configProvided)" \
        "$(grep -c "name: ${v}\$" "${TS}" | xargs)" "1"
    assert_eq "${v}: accepted by the suite (Import User Variable)" \
        "$(grep -c "Import User Variable    ${v}\$" "${RB}" | xargs)" "1"
    assert_eq "${v}: visible to the scripts (env dict)" \
        "$(grep -c "\"${v}\":" "${RB}" | xargs)" "1"
done <<< "${DOCUMENTED}"

# =============================================================================
# Every check script runs `set -x`, and the access token is a live OAuth bearer
# credential valid for about an hour. Under xtrace it was written into the task's
# captured output on every run -- at the ASSIGNMENT, at the emptiness test, and
# at each request, so suppressing any one of those is not enough.
#
# The gcloud stub mints a known sentinel, so this asserts on the real trace of
# the real scripts rather than on the shape of the source.
printf '\n%s== Scenario H -- no access token reaches the xtrace stream%s\n' "${BLUE}" "${NC}"
scenario "  (running every check under the stub)" "${HERE}/fixtures/main"
for s in ${CHECKS}; do
    assert_eq "${s}: token never appears in the trace" \
        "$(grep -c 'offline-fake-token' "${s}.log" || true)" "0"
done
# ...and the suppression must not have swallowed the failure path with it.
scenario "  (and again with no token available)" "${HERE}/fixtures/main" GCLOUD_NO_TOKEN=1
for s in ${CHECKS}; do
    assert_eq "${s}: a missing token is still reported, not silently swallowed" \
        "$(issues "$(issuefile_for "${s}")")" "1"
done

# =============================================================================
# The key-shape probe is pure shell, so unlike the rest of the runbook it can be
# exercised for real. Extracted from runbook.robot rather than copied, so the
# thing under test is the string that actually ships -- a copy would drift and
# then assert about itself.
printf '\n%s== Scenario I -- key shape probe (behavioural)%s\n' "${BLUE}" "${NC}"
rm -rf "${WORK}"; mkdir -p "${WORK}"; cd "${WORK}" || exit 1

# shellcheck disable=SC2016
PROBE=$(grep -F 'echo KEY_MISSING' "${RB}" \
    | sed -e 's/^[[:space:]]*\.\.\.[[:space:]]*cmd=//' -e 's/\${gcp_credentials\.key}/testkey/')
probe() { eval "${PROBE}"; }

rm -f testkey
assert_eq "absent key file reports KEY_MISSING" "$(probe)" "KEY_MISSING"
: > testkey
assert_eq "empty key file reports KEY_EMPTY" "$(probe)" "KEY_EMPTY"

# The case that matters: gcloud reports a base64-encoded key with the same
# ".p12 keys" error as a missing one. One message, three different things to fix.
printf 'eyJ0eXBlIjoic2VydmljZV9hY2NvdW50In0=' > testkey
assert_eq "base64-encoded key reports KEY_NOT_JSON" "$(probe)" "KEY_NOT_JSON"

printf '{"type":"service_account","project_id":"p"}' > testkey
assert_eq "well-formed key reports KEY_JSON" "$(probe)" "KEY_JSON"
printf '\n   {"type":"service_account","project_id":"p"}' > testkey
assert_eq "leading whitespace still reads as KEY_JSON" "$(probe)" "KEY_JSON"

# The probe's output lands in an issue, so it must carry the shape and none of
# the contents. Checked on BOTH branches: the not-JSON path is where a leak is
# likeliest, since that is where someone reaches for `cat` to explain what the
# file actually was.
for shape_case in '{"private_key":"LEAKCANARY"}' 'LEAKCANARY-not-json-at-all'; do
    printf '%s' "${shape_case}" > testkey
    assert_eq "probe emits a sentinel, never key bytes (${shape_case:0:12}...)" \
        "$(probe | grep -c 'LEAKCANARY' || true)" "0"
done
rm -f testkey

# =============================================================================
# The .test harness itself. None of this can be exercised behaviourally here --
# it provisions cloud resources and runs docker -- so it is checked statically.
# Every assertion below corresponds to a way the harness could report success
# while having done nothing, or do real damage to a shared org.
printf '\n%s== Scenario J -- .test harness wiring (static)%s\n' "${BLUE}" "${NC}"
cd "${HERE}" || exit 1
TASKFILE="${BUNDLE}/.test/Taskfile.yaml"
# Comments stripped FIRST. The Taskfile now explains each of these hazards in
# prose, and several of those comments quote the very string being forbidden --
# `runwhen-local:latest` in the override hint, the old ajv idiom in the note
# about why it was wrong. Matching the whole file would fail on the
# documentation rather than on the code.
TF_CODE="$(grep -v "^[[:space:]]*#" "${TASKFILE}")"

# THE BLOCKING ONE. google_project_service defaults to disable_on_destroy = true
# and `task clean` runs `terraform destroy -auto-approve`, so tearing down this
# bundle would have attempted to DISABLE apigee.googleapis.com while a live
# organization, a runtime instance and three sibling bundles' fixtures depended
# on it. This bundle is a read-only guest; the API belongs to
# gcp-apigee-environment-health's state.
#
# Comments are stripped first: the file explains the hazard in prose, and
# matching that would pass on the documentation rather than on the code.
TF_MAIN_CODE="$(grep -v '^ *#' "${BUNDLE}/.test/terraform/main.tf")"
assert_hasnt "terraform does not claim ownership of any project API" \
    "${TF_MAIN_CODE}" "google_project_service"
assert_hasnt "  ...so nothing here can disable Apigee under the shared org" \
    "${TF_MAIN_CODE}" "apigee.googleapis.com"

# Project-wide token creator permits impersonating every service account in the
# project, including the siblings'. Nothing here impersonates anything.
assert_hasnt "no project-wide serviceAccountTokenCreator binding" \
    "${TF_MAIN_CODE}" "roles/iam.serviceAccountTokenCreator"
assert_has "  ...only the two roles the checks need (apigee)" \
    "${TF_MAIN_CODE}" "roles/apigee.readOnlyAdmin"
assert_has "  ...and monitoring" "${TF_MAIN_CODE}" "roles/monitoring.viewer"

# .test/README.md step 3 told operators to export "the service account key
# produced for the reader" while no key resource was ever declared.
assert_has "the reader key the README refers to actually exists" \
    "${TF_MAIN_CODE}" "google_service_account_key"

# Fixture provisioning must exit non-zero when it cannot run.
assert_hasnt "build-terraform-infra no longer skips silently and reports success" \
    "${TF_CODE}" "Skipping Terraform apply"
assert_has "  ...it resolves credentials, which exit non-zero when absent" \
    "${TF_CODE}" ". ../load-credentials.sh"
assert_eq "the shared credential contract ships" \
    "$([ -f "${BUNDLE}/.test/load-credentials.sh" ] && echo yes || echo no)" "yes"

# `ajv ... && echo valid || echo invalid` swallowed the failure: the block's exit
# status was the trailing `rm -rf`, so an invalid rule printed "is invalid" and
# the task still exited 0.
# The distinguishing feature of the broken form is the `&& echo ... || echo`
# chain, not the message: the fixed code still says "is invalid." inside a
# branch that also increments a failure counter.
# shellcheck disable=SC2016
assert_hasnt "generation-rule validation cannot swallow a failure" \
    "${TF_CODE}" '|| echo "$yaml_file is invalid."'
assert_has "  ...it counts failures and exits non-zero" \
    "${TF_CODE}" "generation rule(s) failed validation."
assert_has "  ...the schema download is checked" "${TF_CODE}" "curl -fsS -o"
assert_has "  ...and sanity-checked as JSON"     "${TF_CODE}" "is not valid JSON"
assert_has "  ...and an empty rule set is an error" \
    "${TF_CODE}" "no generation rules found under"

# On an image whose registry predates Apigee support, discovery exits 0 with
# ZERO SLXs, which reads as "the rule matched nothing" rather than as an image
# problem.
assert_hasnt "the discovery image is pinned, not :latest" \
    "${TF_CODE}" "runwhen-local:latest"
assert_has "  ...and the image is probed for the gated resource type first" \
    "${TF_CODE}" "does not know the resource type gcp_apigee_organizations"

# The credential-free tiers are the ones that gate a PR and the ones most people
# should run first, so the .test README has to name them.
TEST_README="$(cat "${BUNDLE}/.test/README.md")"
assert_has "the .test README documents the offline tier" "${TEST_README}" "offline/run.sh"
assert_has "  ...and the render tier"                    "${TEST_README}" "render/run.sh"


# --- Standard task vocabulary (static) ---------------------------------------
# Every gcp-apigee-* bundle declares the same task names with the same chains,
# so `task --list` reads identically in all five. Asserting on it here is what
# stops the five drifting apart again one convenience rename at a time.
TASKFILE_V="${BUNDLE}/.test/Taskfile.yaml"
TF_V="$(grep -v "^[[:space:]]*#" "${TASKFILE_V}")"
DEFAULT_CHAIN_V="$(awk '/^  default:/{f=1;next} /^  [a-z-]+:/{f=0} f' "${TASKFILE_V}")"
CI_CHAIN_V="$(awk '/^  ci:/{f=1;next} /^  [a-z-]+:/{f=0} f' "${TASKFILE_V}")"
CLEAN_CHAIN_V="$(awk '/^  clean:/{f=1;next} /^  [a-z-]+:/{f=0} f' "${TASKFILE_V}")"

for t in ci test-offline test-render validate-generation-rules build-infra \
         test-live check-and-cleanup-fixtures check-unpushed-commits \
         generate-rwl-config run-rwl-discovery clean-rwl-discovery clean \
         bootstrap-prerequisites destroy-prerequisites preflight; do
    assert_has "task '${t}' is declared" "${TF_V}" "
  ${t}:"
done
# The old names. A leftover alias is one more thing an operator has to know,
# and `...-terraform` names the mechanism -- wrongly, for the bundles whose
# fixtures are REST objects Terraform never sees.
for t in run-mock-tests test-issue-generation check-and-cleanup-terraform; do
    assert_hasnt "the old name '${t}' is gone" "${TF_V}" "
  ${t}:"
done

assert_has "default runs the credential-free gate first" "${DEFAULT_CHAIN_V}" "task: ci"
assert_has "  ...then the live assertion tier"           "${DEFAULT_CHAIN_V}" "task: test-live"
assert_has "  ...and reaches discovery"                  "${DEFAULT_CHAIN_V}" "run-rwl-discovery"
assert_has "ci runs the offline tier"                    "${CI_CHAIN_V}" "task: test-offline"
assert_has "  ...the render tier"                        "${CI_CHAIN_V}" "task: test-render"
assert_has "  ...validates the generation rule"          "${CI_CHAIN_V}" "validate-generation-rules"
assert_has "  ...and checks the shared substrate"        "${CI_CHAIN_V}" "check-shared-drift"

# `task clean` must not require RunWhen Platform credentials. It used to call
# delete-slxs -> check-rwp-config, which exits 1 without RW_WORKSPACE/RW_API_URL/
# RW_PAT -- so clean-rwl-discovery never ran and a root-owned output/ was left
# behind after every local run on a machine with no Platform credentials.
assert_hasnt "clean does not require Platform credentials" "${CLEAN_CHAIN_V}" "delete-slxs"
assert_has "  ...and still removes the discovery output"  "${CLEAN_CHAIN_V}" "clean-rwl-discovery"

# The RunWhen Platform tasks come from the collection-wide Taskfile. The copies
# these bundles carried had all drifted to the v3 /branches/main/ endpoint.
assert_has "the shared RW taskfile is included" "${TF_V}" "../../.test-tasks/Taskfile.yaml"
assert_hasnt "  ...so no stale v3 branch endpoint is copied in here" \
    "${TF_V}" "branches/main/slxs"

# On an image whose registry predates Apigee support, discovery exits 0 with
# ZERO SLXs, which reads as "the rule matched nothing" rather than as an image
# problem.
assert_hasnt "the discovery image is pinned, not :latest" "${TF_V}" "runwhen-local:latest"
assert_has "  ...and probed for the gated resource type first" \
    "${TF_V}" "does not know the resource type gcp_apigee_organizations"

# The shared substrate must actually ship, or bootstrap-prerequisites is a
# task that names a file nobody added.
assert_eq "the shared prerequisites script ships" \
    "$([ -f "${BUNDLE}/.test/apigee_prerequisites.sh" ] && echo yes || echo no)" "yes"
assert_eq "the drift checker ships" \
    "$([ -f "${BUNDLE}/.test/check-shared-drift.sh" ] && echo yes || echo no)" "yes"
assert_eq "the live tier ships" \
    "$([ -f "${BUNDLE}/.test/test-live.sh" ] && echo yes || echo no)" "yes"

# The offline tier must be unable to REACH live credentials, not merely not use
# them. Without a gcloud stub first on PATH, the token fallback in the check
# scripts finds the REAL gcloud, so a "credential-free" run on any machine with
# ambient credentials mints a live ya29 token -- and then traces it. The stub
# directory is named bin in every bundle; it was mock in one and stubs in
# another, which is how one of them came to be missing the gcloud stub entirely.
assert_eq "the offline tier stubs gcloud" \
    "$([ -x "${BUNDLE}/.test/offline/bin/gcloud" ] && echo yes || echo no)" "yes"
assert_eq "  ...and curl" \
    "$([ -x "${BUNDLE}/.test/offline/bin/curl" ] && echo yes || echo no)" "yes"


# --- C9: the substrate contract (static) -------------------------------------
# Environments and the runtime instance are substrate, not any one bundle's
# fixtures: an EVALUATION org caps them at 2 and 1 respectively, and a capped
# resource is shared by definition. Four of the five bundles need the
# environments and none can create its own.
assert_has "build-infra bootstraps the substrate itself" \
    "$(awk '/^  build-infra:/{f=1;next} /^  [a-z-]+:/{f=0} f' "${TASKFILE_V}")" "task: bootstrap-prerequisites"
assert_has "  ...and preflights it before creating anything" \
    "$(awk '/^  build-infra:/{f=1;next} /^  [a-z-]+:/{f=0} f' "${TASKFILE_V}")" "task: preflight"
assert_eq "the shared preflight ships" \
    "$([ -f "${BUNDLE}/.test/apigee_preflight.sh" ] && echo yes || echo no)" "yes"

# The contract has to be written down where the next person looks, because the
# unattached environment WILL otherwise get "tidied up" -- and attaching it
# deletes environment-health's known-positive for check_instance_attachments,
# making that check pass because there is nothing to find.
PREREQ_V="$(cat "${BUNDLE}/.test/apigee_prerequisites.sh")"
assert_has "the substrate contract is stated in the shared script" \
    "${PREREQ_V}" "THE SUBSTRATE CONTRACT"
assert_has "  ...including the unattached-is-a-fixture invariant" \
    "${PREREQ_V}" "BEING UNATTACHED IS A FIXTURE, NOT A DEFECT"
assert_has "bootstrap creates both substrate environments" \
    "${PREREQ_V}" "_ensure_environment \"\${APIGEE_ENV_UNATTACHED}\""
assert_has "  ...and the runtime instance" "${PREREQ_V}" "_ensure_instance"
assert_has "  ...and attaches only the healthy one" \
    "${PREREQ_V}" "_ensure_attachment \"\${APIGEE_INSTANCE}\" \"\${APIGEE_ENV_HEALTHY}\""
# Concurrency: two bundles may bootstrap at once, and the loser must no-op.
assert_has "environment creation tolerates a concurrent creator" "${PREREQ_V}" "409)     note \"environment"

# The preflight must assert the contract BY NAME. A count cannot catch the
# failure that motivated it: with one environment instead of two, proxy-health's
# bootstrap skips its drift fixture behind `if [ -n "$env2" ]` and
# check_revision_drift.sh then reports clean because nothing was created to
# drift.
PREFLIGHT_V="$(cat "${BUNDLE}/.test/apigee_preflight.sh")"
assert_has "preflight asserts the environments by name" \
    "${PREFLIGHT_V}" "for want in \"\${APIGEE_ENV_HEALTHY}\" \"\${APIGEE_ENV_UNATTACHED}\""
assert_has "  ...reads /environments as the bare array the API returns" \
    "${PREFLIGHT_V}" 'if type=="array" then .[]'
assert_has "  ...requires a runtime instance" "${PREFLIGHT_V}" "has no runtime instance"
assert_has "  ...and that the healthy environment is attached" \
    "${PREFLIGHT_V}" "is not attached to runtime instance"
assert_has "  ...and warns if the unattached fixture was attached" \
    "${PREFLIGHT_V}" "IS attached to"

# =============================================================================
printf '\n%s== summary%s\n' "${BLUE}" "${NC}"
printf '  %s%d passed%s, %s%d failed%s\n' "${GREEN}" "${PASS}" "${NC}" \
    "$([ "${FAIL}" -gt 0 ] && echo "${RED}" || echo "${GREEN}")" "${FAIL}" "${NC}"
if [ "${FAIL}" -gt 0 ]; then
    printf '  logs: %s\n' "${WORK}"
    if [ "${VERBOSE}" = "-v" ]; then
        for f in "${WORK}"/*.log; do printf '\n--- %s\n' "$f"; cat "$f"; done
    fi
    exit 1
fi
rm -rf "${WORK}"
exit 0
