apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  platform: gcp
  generationRules:
    - resourceTypes:
        - gcp_compute_instance_groups
        - gcp_compute_instance_group_managers
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: [name]
          mode: substring
      slxs:
        - baseName: gcp-compute-instancegroup-health
          qualifiers: ["resource"]
          baseTemplateName: gcp-compute-instancegroup-health
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: sli
            - type: slo
            - type: runbook
              templateName: gcp-compute-instancegroup-health-taskset.yaml
