apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  platform: azure
  generationRules:
    - resourceTypes:
        - azure_network_security_groups
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: [name]
          mode: substring
      slxs:
        - baseName: azure-nsg-desired-state-drift
          qualifiers: ["resource", "resource_group", "subscription_id"]
          baseTemplateName: azure-nsg-desired-state-drift
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: runbook
              templateName: azure-nsg-desired-state-drift-taskset.yaml
