apiVersion: v1
kind: Namespace
metadata:
  name: test-litellm-proxy-health

---
apiVersion: v1
kind: Service
metadata:
  name: litellm-proxy
  namespace: test-litellm-proxy-health
  labels:
    app.kubernetes.io/name: litellm
spec:
  ports:
    - port: 4000
      name: http
      protocol: TCP
  clusterIP: None
  selector:
    app.kubernetes.io/name: litellm
