apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  platform: mailgun
  generationRules:
    - resourceTypes:
        - mailgun_sending_domain
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: ["name"]
          mode: substring
      slxs:
        - baseName: mailgun-domain-health
          qualifiers: ["MAILGUN_SENDING_DOMAIN", "MAILGUN_API_REGION"]
          baseTemplateName: mailgun-sending-domain-health
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: sli
            - type: runbook
              templateName: mailgun-sending-domain-health-taskset.yaml
