apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  platform: aws
  generationRules:
    - resourceTypes:
        - aws_sqs_queues
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: ["name"]
          mode: substring
      slxs:
        - baseName: aws-sqs-dlq-investigation
          qualifiers: ["region", "account_id"]
          baseTemplateName: aws-sqs-dlq-investigation
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: sli
            - type: runbook
              templateName: aws-sqs-dlq-investigation-taskset.yaml
