apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
    - resourceTypes:
        - service
      matchRules:
        - type: pattern
          pattern: "litellm"
          properties: [name]
          mode: substring
      slxs:
        - baseName: litellm-proxy-hc
          qualifiers: ["resource", "namespace", "cluster"]
          baseTemplateName: k8s-litellm-proxy-health
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: sli
            - type: runbook
              templateName: k8s-litellm-proxy-health-taskset.yaml
