apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  platform: azure
  generationRules:
    - resourceTypes:
        - azure_storage_accounts
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: [name]
          mode: substring
      slxs:
        - baseName: azure-storage-investigation
          qualifiers: ["resource", "subscription_id", "resource_group"]
          baseTemplateName: azure-storage-account-investigation
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: sli
            - type: runbook
              templateName: azure-storage-account-investigation-taskset.yaml
