apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
    - resourceTypes:
        - postgresclusters.postgres-operator.crunchydata.com
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: [name]
          mode: substring
      slxs:
        - baseName: pgb-pg-spec
          shortenedBaseName: pgb-pg-spec
          qualifiers: ["resource", "namespace", "cluster"]
          baseTemplateName: k8s-postgrescluster-pgbouncer-spec
          levelOfDetail: detailed
          outputItems:
            - type: slx
            - type: runbook
              templateName: k8s-postgrescluster-pgbouncer-spec-taskset.yaml
