apiVersion: runwhen.com/v1
kind: Runbook
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  location: {{default_location}}
  codeBundle:
    {% if repo_url %}
    repoUrl: {{repo_url}}
    {% else %}
    repoUrl: https://github.com/runwhen-contrib/rw-cli-codecollection.git
    {% endif %}
    {% if ref %}
    ref: {{ref}}
    {% else %}
    ref: main
    {% endif %}
    pathToRobot: codebundles/ovirt-engine-health/runbook.robot
  configProvided:
    - name: OVIRT_ENGINE_URL
      value: {{custom.ovirt_engine_url}}
  secretsProvided:
    - name: OVIRT_USERNAME
      workspaceKey: {{custom.ovirt_username}}
    - name: OVIRT_PASSWORD
      workspaceKey: {{custom.ovirt_password}}
    {% if custom.ovirt_ca_cert %}
    - name: OVIRT_CA_CERT
      workspaceKey: {{custom.ovirt_ca_cert}}
    {% endif %}
